name: Deploy Backend a EC2

on:
  push:
    branches: [deploy]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: despachos-backend
  EC2_HOST: ${{ secrets.EC2_BACKEND_HOST }}
  EC2_USER: ec2-user
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Construir y publicar imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Desplegar en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/backend-app
            echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" > .env
            docker compose pull backend-despachos
            docker compose up -d --no-deps backend-despachos
            docker image prune -f